=== FrankBuchholz/frun-csa-policies-best-practices/Schema/csa_policy.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified"><xs:simpleType name="yesnoType"><xs:restriction base="xs:string"><xs:enumeration value="Yes"/><xs:enumeration value="No"/></xs:restriction></xs:simpleType><xs:simpleType name="name_extendedType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/></xs:restriction></xs:simpleType><xs:simpleType name="sci_idType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="20"/></xs:restriction></xs:simpleType><xs:simpleType name="system_typeType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="20"/></xs:restriction></xs:simpleType><xs:simpleType name="hierarchy_levelType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="1"/><xs:pattern value="[23456]"/></xs:restriction></xs:simpleType><xs:simpleType name="descType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/></xs:restriction></xs:simpleType><xs:simpleType name="idType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="20"/></xs:restriction></xs:simpleType><xs:simpleType name="not_foundType"><xs:restriction base="xs:string"><xs:enumeration value="positive"/><xs:enumeration value="negative"/></xs:restriction></xs:simpleType><xs:simpleType name="system_rolesType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="250"/></xs:restriction></xs:simpleType><xs:simpleType name="store_attributeType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="280"/></xs:restriction></xs:simpleType><xs:simpleType name="operatorType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/><xs:pattern value="[Ee][Xx][Ii][Ss][Tt]($|:[\w\d_]{1,256})|[Nn][Oo][Tt]_[Ee][Xx][Ii][Ss][Tt]($|:[\w\d_]{1,256})|[Cc][Hh][Ee][Cc][Kk]_[Nn][Oo][Tt][Ee]|[Cc][Hh][Ee][Cc][Kk]_[Nn][Oo][Tt][Ee]:[0-9]{10}"/></xs:restriction></xs:simpleType><xs:simpleType name="nameType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/></xs:restriction></xs:simpleType><xs:element name="targetsystem"><xs:complexType><xs:sequence><xs:element maxOccurs="unbounded" minOccurs="1" name="configstore"><xs:complexType><xs:sequence><xs:element maxOccurs="unbounded" minOccurs="1" name="checkitem"><xs:complexType><xs:sequence><xs:element name="compliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="complianttext" type="xs:string"/><xs:element name="noncompliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="noncomplianttext" type="xs:string"/><xs:element maxOccurs="unbounded" minOccurs="0" name="joinstore"><xs:complexType><xs:sequence><xs:element name="joincompliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="joincomplianttext" type="xs:string"/><xs:element name="joinnoncompliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="joinnoncomplianttext" type="xs:string"/></xs:sequence><xs:attribute name="name" type="xs:string" use="required"/><xs:attribute default="Yes" name="minus" type="yesnoType" use="optional"/><xs:attribute name="name_extended" type="name_extendedType" use="optional"/><xs:attribute default="No" name="no_data_found" type="yesnoType" use="optional"/><xs:attribute default="No" name="not_in_output" type="yesnoType" use="optional"/><xs:attribute name="sci_id" type="sci_idType" use="optional"/><xs:attribute name="system_type" type="system_typeType" use="optional"/><xs:attribute name="hierarchy_level" type="hierarchy_levelType" use="optional"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="desc" type="descType" use="required"/><xs:attribute name="id" type="idType" use="required"/><xs:attribute default="negative" name="not_found" type="not_foundType" use="optional"/><xs:attribute name="operator" type="operatorType" use="optional"/><xs:attribute name="system_roles" type="system_rolesType" use="optional"/><xs:attribute name="store_attribute" type="store_attributeType" use="optional"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="name" type="nameType" use="required"/><xs:attribute name="name_extended" type="name_extendedType" use="optional"/><xs:attribute name="sci_id" type="sci_idType" use="optional"/><xs:attribute name="system_type" type="system_typeType" use="optional"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="desc" type="descType" use="required"/><xs:attribute name="id" type="idType" use="required"/><xs:attribute default="Yes" name="multisql" type="yesnoType"/></xs:complexType></xs:element></xs:schema>

=== FrankBuchholz/frun-csa-policies-best-practices/NotesPolicies/HANA/HANASecNotes_2022_04.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
This FRUN CSA policy contains rules to check the following Note related to tehe mitigation of Log4j vulnerability in (HANA):
[p1-CVSS 9.8] 3189428 - [CVE-2022-22965] Remote Code Execution vulnerability associated with Spring Framework used in SAP HANA Extended Application Services(Version 4) 
                check for SAP_EXTENDED_APP_SERVICES
		+ manual activity  
[p2-CVSS-7.5] 3111311 BC-CST-WDP - [CVE-2022-28772]Denial of service (DOS) in SAP Web Dispatcher and SAP Netweaver (Internet Communication Manager)(Version 7)
       check for SAP_EXTENDED_APP_SERVICES
[p3-CVSS-4.9] 3111293 BC-CST-WDP - [CVE-2022-28773] Denial of service (DOS) in SAP Web Dispatcher and SAP Netweaver (Internet Communication Manager) (Version 6)
        Check for Hana Version

PatchDay: 2022-04 
Version:  001
Date:     12.04.2022
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="SNotes of PatchDay: 2022-04 (HANA)" id="2022-04_HANA" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <!--[p1-CVSS 9.8] 3189428 - [CVE-2022-22965] Remote Code Execution vulnerability associated with Spring Framework used in SAP HANA Extended Application Services(Version 4)-->
  <configstore name="COMP_LEVEL" sci_id ="S00343">
    <checkitem desc="[p1-CVSS 9.8] XS Advanced version which note 0003189428v4 recommends" id="3189428">
      <compliant>    COMPONENT = 'SAP_EXTENDED_APP_SERVICES' and VERSION = '1' and lpad(PATCH,4,'0') &gt;= '0145'   </compliant>
      <complianttext/>
      <noncompliant> COMPONENT = 'SAP_EXTENDED_APP_SERVICES' and VERSION = '1' and lpad(PATCH,4,'0') &lt;  '0145'   </noncompliant>
      <noncomplianttext/>
      <joinstore name="COMP_LEVEL" sci_id ="S00343" no_data_found="Yes">
        <joincompliant>COMPONENT = 'SAP_EXTENDED_APP_SERVICES'</joincompliant>
        <joinnoncompliant>COMPONENT = 'SAP_EXTENDED_APP_SERVICES'</joinnoncompliant>
      </joinstore>
    </checkitem>
  <!--[p2-CVSS-7.5] 3111311 BC-CST-WDP - [CVE-2022-28772]Denial of service (DOS) in SAP Web Dispatcher and SAP Netweaver (Internet Communication Manager)(Version 7) -->
    <checkitem desc="[p2-CVS-7.5] XS Advanced version which note 0003111311v7 recommends" id="3111311">
      <compliant>    COMPONENT = 'SAP_EXTENDED_APP_SERVICES' and VERSION = '1' and lpad(PATCH,4,'0') &gt;= '0143'   </compliant>
      <complianttext/>
      <noncompliant> COMPONENT = 'SAP_EXTENDED_APP_SERVICES' and VERSION = '1' and lpad(PATCH,4,'0') &lt;  '0143'   </noncompliant>
      <noncomplianttext/>
      <joinstore name="COMP_LEVEL" sci_id ="S00343" no_data_found="Yes">
        <joincompliant>COMPONENT = 'SAP_EXTENDED_APP_SERVICES'</joincompliant>
        <joinnoncompliant>COMPONENT = 'SAP_EXTENDED_APP_SERVICES'</joinnoncompliant>
      </joinstore>
    </checkitem>
  </configstore>
  <!--  [p3-CVSS-4.9] 3111293 BC-CST-WDP - [CVE-2022-28773] Denial of service (DOS) in SAP Web Dispatcher and SAP Netweaver (Internet Communication Manager) (Version 6)  -->
  <configstore name="HDB_VERSION">
    <checkitem desc="[p3-CVSS-4.9] Note 3111293 requires revision update" id="0003111293">
      <compliant>
                 (  (NAME = 'VERSION' AND substring(VALUE,0,7) = '2.00.06' AND substring(VALUE,0,8) &gt;= '2.00.061')
                 OR (NAME = 'VERSION' AND substring(VALUE,0,7) = '2.00.05' AND substring(VALUE,0,11) &gt;= '2.00.059.02')
                 OR (NAME = 'VERSION' AND substring(VALUE,0,7) &gt; '2.00.06' ) )  
      </compliant>
      <noncompliant>
                (   (NAME = 'VERSION' AND substring(VALUE,0,4) = '2.00' AND substring(VALUE,0,7) &lt; '2.00.05')
	         OR (NAME = 'VERSION' AND substring(VALUE,0,7) = '2.00.06' AND substring(VALUE,0,6) &lt; '2.00.061') 
                 OR (NAME = 'VERSION' AND substring(VALUE,0,7) = '2.00.05' AND substring(VALUE,0,11) &lt; '2.00.059.02')
                 OR (NAME = 'VERSION' AND substring(VALUE,0,4) = '1.00' ) )
      </noncompliant>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v2.2/ABAP_SYSTEM/BL2_OBSCNT-A.xml
<?xml version="1.0" encoding="utf-8"?>
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="[BL 2.2] Obsolete Clients - ABAP" id="BL22_OBSCNT-A" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <!-- OBSCNT-A: Obsolete Clients in ABAP -->
  <configstore name="CLIENTS">
    <checkitem desc="[p2-STANDARD] Obsolete Client 066 must not exist." id="OBSCNT-A.1" operator="NOT_EXIST">
      <compliant>    MANDT = '066'    </compliant>
      <noncompliant> MANDT = '066'    </noncompliant>
    </checkitem>
    <checkitem desc="[p2-STANDARD] Template Client 001 must be deleted if not used" id="OBSCNT-A.2" operator="NOT_EXIST">
      <compliant>    MANDT = '001'    </compliant>
      <noncompliant> MANDT = '001'    </noncompliant>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v2.2/ABAP_SYSTEM/BL2_SCRIPT-A.xml
<?xml version="1.0" encoding="utf-8"?>
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="[BL 2.2] Scripting Protection - ABAP" id="BL22_SCRIPT-A" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <!-- SCRIPT-A: Scripting Protection â€“ ABAP -->
  <!-- Possible values: TRUE, FALSE, 0, 1, ON, OFF, YES, NO
       Related notes: 2163298, 2163298  -->
  <configstore name="ABAP_INSTANCE_PAHI" sci_id="">
    <checkitem desc="[p3-[EXTENDED] Scripting Protection profile parameter (sapgui/nwbc_scripting)" id="SCRIPT-A_a.1">
      <compliant>NAME = 'sapgui/nwbc_scripting' and VALUE = 'FALSE' </compliant>
      <complianttext/>
      <noncompliant>NAME = 'sapgui/nwbc_scripting' and not VALUE = 'FALSE'</noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-[EXTENDED] Scripting Protection profile parameter (sapgui/user_scripting)" id="SCRIPT-A_a.2">
      <compliant>    NAME = 'sapgui/user_scripting' and VALUE = 'FALSE' </compliant>
      <complianttext/>
      <noncompliant> NAME = 'sapgui/user_scripting' and not VALUE = 'FALSE'</noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-[EXTENDED] Scripting Protection profile parameter (sapgui/user_scripting_disable_recording)" id="SCRIPT-A_a.3">
      <compliant>    NAME = 'sapgui/user_scripting_disable_recording' and VALUE = 'TRUE' </compliant>
      <complianttext/>
      <noncompliant> NAME = 'sapgui/user_scripting_disable_recording' and not VALUE = 'TRUE'</noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-[EXTENDED] Scripting Protection profile parameter (sapgui/user_scripting_force_notification)" id="SCRIPT-A_a.4">
      <compliant>    NAME = 'sapgui/user_scripting_force_notification' and VALUE = 'TRUE' </compliant>
      <complianttext/>
      <noncompliant> NAME = 'sapgui/user_scripting_force_notification' and not VALUE = 'TRUE'</noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-[EXTENDED] Scripting Protection profile parameter (sapgui/user_scripting_per_user)" id="SCRIPT-A_a.5">
      <compliant>    NAME = 'sapgui/user_scripting_per_user' and VALUE = 'TRUE' </compliant>
      <complianttext/>
      <noncompliant> NAME = 'sapgui/user_scripting_per_user' and not VALUE = 'TRUE'</noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-[EXTENDED] Scripting Protection profile parameter (sapgui/user_scripting_set_readonly)" id="SCRIPT-A_a.6">
      <compliant>    NAME = 'sapgui/user_scripting_set_readonly' and VALUE = 'TRUE' </compliant>
      <complianttext/>
      <noncompliant> NAME = 'sapgui/user_scripting_set_readonly' and not VALUE = 'TRUE'</noncompliant>
      <noncomplianttext/>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v2.4/ABAP_ALL/3ACHANGE.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 
Reference:   SAP Security Baseline Template v2.4 (2022/12)
Link:        https://support.sap.com/content/dam/support/en_us/library/ssp/offerings-and-programs/support-services/sap-security-optimization-services-portfolio/Security_Baseline_Template_V2.zip
Version:     001
Date:        2023-04-28
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="[BL2.4] Change Protection of Prod System (ABAP)" id="3ACHANGE" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <!-- id= CHANGE-A_d, e, f: Transport Parameters available in Focused Run as of FRUN 3.0 FP00 -->
  <configstore name="TRANSPORT_TOOL">
    <checkitem desc="[p3-EXTENDED] Transport Parameter RECCLIENT is activated" id="CHANGE-A_d">
      <compliant>    NAME = 'RECCLIENT'  and (VALUE != 'OFF' and length(VALUE) &gt; 0) </compliant>
      <complianttext/>
      <noncompliant> NAME = 'RECCLIENT'  and (VALUE = 'OFF' or length(VALUE) = 0) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Transport Parameter VERS_AT_IMP is activated" id="CHANGE-A_e.1" system_roles="DEV">
      <compliant>    NAME = 'VERS_AT_EXP'  and VALUE = '1' </compliant>
      <complianttext/>
      <noncompliant> NAME = 'VERS_AT_EXP'  and not VALUE = '1' </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Transport Parameter VERS_AT_IMP is activated in Prod." id="CHANGE-A_e.2" system_roles="PROD">
      <compliant>    NAME = 'VERS_AT_IMP'  and VALUE = 'ALWAYS'  </compliant>
      <complianttext/>
      <noncompliant> NAME = 'VERS_AT_IMP'  and VALUE != 'ALWAYS' </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Transport Parameter TP_RELEASE is compliant" id="CHANGE-A_g.1">
      <compliant>    NAME = 'TP_RELEASE'  and VALUE &gt;= '380.44.90'  </compliant>
      <complianttext/>
      <noncompliant> NAME = 'TP_RELEASE'  and VALUE &lt; '380.44.90' </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Transport Parameter TP_VERSION is compliant" id="CHANGE-A_g.2">
      <compliant>    NAME = 'TP_VERSION'  and VALUE &gt;= '380'  </compliant>
      <complianttext/>
      <noncompliant> NAME = 'TP_VERSION'  and VALUE &lt; '380' </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Transport Parameter CHK_CRIOBJ_AT_EXPORT is compliant" id="CHANGE-A_h" system_roles="DEV">
      <compliant>    NAME = 'CHK_CRIOBJ_AT_EXPORT'  and ( VALUE = 'W' or VALUE = 'E' ) </compliant>
      <complianttext/>
      <noncompliant> NAME = 'CHK_CRIOBJ_AT_EXPORT'  and ( VALUE = 'W' or VALUE = 'E' ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
  </configstore>
  <!-- END of Transport Parameters available as of FRUN 3.0 FP00 -->
  <configstore name="SAP_KERNEL">
    <checkitem desc="[p3-EXTENDED] Kernel release which note 2405918 recommends" id="CHANGE-A_g.3">
      <compliant>    NAME = 'KERN_REL' and 
                   ( ( substring(VALUE,0,3) &gt; '773' ) or
                     ( substring(VALUE,0,3) = '773' ) or
                     ( substring(VALUE,0,3) = '753') or
                     ( substring(VALUE,0,3) = '749') or
                     ( substring(VALUE,0,3) = '745') or
                     ( substring(VALUE,0,3) = '722') or
                     ( substring(VALUE,0,3) = '721') )
      </compliant>
      <noncompliant> NAME = 'KERN_REL' and not
                   ( ( substring(VALUE,0,3) &gt; '773' ) or
                     ( substring(VALUE,0,3) = '773' ) or
                     ( substring(VALUE,0,3) = '753') or
                     ( substring(VALUE,0,3) = '749') or
                     ( substring(VALUE,0,3) = '745') or
                     ( substring(VALUE,0,3) = '722') or
                     ( substring(VALUE,0,3) = '721') )
      </noncompliant>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Kernel patchlevel which note 2671160 recommends" id="CHANGE-A_g.3">
      <compliant>    NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &gt;= '1112'</compliant>
      <noncompliant> NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &lt; '1112'</noncompliant>
      <joinstore name="SAP_KERNEL" no_data_found="Yes">
        <joincompliant>      NAME = 'KERN_REL' and VALUE = '721_REL'</joincompliant>
        <joinnoncompliant>   NAME = 'KERN_REL' and VALUE = '721_REL'</joinnoncompliant>
      </joinstore>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Kernel patchlevel which note 2671160 recommends" id="CHANGE-A_g.3">
      <compliant>    NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &gt;= '0625'</compliant>
      <noncompliant> NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &lt; '0625'</noncompliant>
      <joinstore name="SAP_KERNEL" no_data_found="Yes">
        <joincompliant>      NAME = 'KERN_REL' and VALUE = '722_REL'</joincompliant>
        <joinnoncompliant>   NAME = 'KERN_REL' and VALUE = '722_REL'</joinnoncompliant>
      </joinstore>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Kernel patchlevel which note 2671160 recommends" id="CHANGE-A_g.3">
      <compliant>    NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &gt;= '0810'</compliant>
      <noncompliant> NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &lt; '0810'</noncompliant>
      <joinstore name="SAP_KERNEL" no_data_found="Yes">
        <joincompliant>      NAME = 'KERN_REL' and VALUE = '745_REL'</joincompliant>
        <joinnoncompliant>   NAME = 'KERN_REL' and VALUE = '745_REL'</joinnoncompliant>
      </joinstore>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Kernel patchlevel which note 2671160 recommends" id="CHANGE-A_g.3">
      <compliant>    NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &gt;= '0521'</compliant>
      <noncompliant> NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &lt; '0521'</noncompliant>
      <joinstore name="SAP_KERNEL" no_data_found="Yes">
        <joincompliant>      NAME = 'KERN_REL' and VALUE = '749_REL'</joincompliant>
        <joinnoncompliant>   NAME = 'KERN_REL' and VALUE = '749_REL'</joinnoncompliant>
      </joinstore>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Kernel patchlevel which note 2671160 recommends" id="CHANGE-A_g.3">
      <compliant>    NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &gt;= '0220'</compliant>
      <noncompliant> NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &lt; '0220'</noncompliant>
      <joinstore name="SAP_KERNEL" no_data_found="Yes">
        <joincompliant>      NAME = 'KERN_REL' and VALUE = '753_REL'</joincompliant>
        <joinnoncompliant>   NAME = 'KERN_REL' and VALUE = '753_REL'</joinnoncompliant>
      </joinstore>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Kernel patchlevel which note 2671160 recommends" id="CHANGE-A_g.3">
      <compliant>    NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &gt;= '0011'</compliant>
      <noncompliant> NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &lt; '0011'</noncompliant>
      <joinstore name="SAP_KERNEL" no_data_found="Yes">
        <joincompliant>      NAME = 'KERN_REL' and VALUE = '773_REL'</joincompliant>
        <joinnoncompliant>   NAME = 'KERN_REL' and VALUE = '773_REL'</joinnoncompliant>
      </joinstore>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Kernel patchlevel which note 2671160 recommends" id="CHANGE-A_g.3">
      <compliant>    NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &gt;= '0000'</compliant>
      <noncompliant> NAME = 'KERN_PATCHLEVEL' and lpad(VALUE,4,'0') &lt; '0000'</noncompliant>
      <joinstore name="SAP_KERNEL" no_data_found="Yes">
        <joincompliant>      NAME = 'KERN_REL' and VALUE = '774_REL'</joincompliant>
        <joinnoncompliant>   NAME = 'KERN_REL' and VALUE = '774_REL'</joinnoncompliant>
      </joinstore>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v2.4/HANA_ALL/1HNETCF.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
Reference:   SAP Security Baseline Template v2.4 (2022/12)
Link:        https://support.sap.com/content/dam/support/en_us/library/ssp/offerings-and-programs/support-services/sap-security-optimization-services-portfolio/Security_Baseline_Template_V2.zip
Version:     001
Date:        2023-04-28
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="[BL2.4] Secure Network Configuration (HANA)" id="1HNETCF" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <configstore name="HDB_PARAMETER">
    <!-- with listeninterface = .global an insecure configuration is more likely than with settings .internal or .local -->
    <checkitem desc="[p1-CRITICAL] HANA internal communication (listeninterface)" id="NETCF-H_a.1">
      <compliant>    FILE_NAME = 'global.ini' and SECT = 'communication'  and NAME = 'listeninterface'  and VALUE != '.global' 
      </compliant>
      <complianttext/>
      <noncompliant> FILE_NAME = 'global.ini' and SECT = 'communication'  and NAME = 'listeninterface'  and VALUE = '.global'
      </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <!--Scale-out systems are usually compliant if internal hostname resolution is configured -->
    <checkitem desc="[p1-CRITICAL] HANA internal communication (listeninterface)" id="NETCF-H_a.2">
      <compliant>    FILE_NAME = 'global.ini' and SECT = 'internal_hostname_resolution' and NAME like '%' and VALUE not like_regexpr '^\s*$'
      </compliant>
      <complianttext> Parameter listeninterface = .internal and Section internal_hostname_resolution is configured </complianttext>
      <noncompliant> FILE_NAME = 'global.ini' and SECT = 'internal_hostname_resolution' and NAME like '%' and VALUE like_regexpr '^\s*$'
      </noncompliant>
      <noncomplianttext> Parameter listeninterface = .internal but Section internal_hostname_resolution is not configured </noncomplianttext>
      <joinstore name="HDB_PARAMETER" no_data_found="Yes">
        <joincompliant>    FILE_NAME = 'global.ini' and SECT = 'communication'  and NAME = 'listeninterface'  and VALUE = '.internal' </joincompliant>
        <joinnoncompliant> FILE_NAME = 'global.ini' and SECT = 'communication'  and NAME = 'listeninterface'  and VALUE = '.internal' </joinnoncompliant>
      </joinstore>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/NotesPolicies/HANA/HANASecNotes_2021_02.xml
<?xml version="1.0" encoding="utf-8"?>
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="HANA NOTES OF PATCHDAY: 2021-02" id="HPATCHDAY_2021-02" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <!--
This FRUN CSA policy contains rules to check the following HANA Security Note:

[p3-CVSS 4.1]  0002992154 HAN-DB-SEC -  [CVE-2021-21474] SAML Assertion Signature MD5 Digest Algorithm Vulnerability in SAP HANA Database

The issue has been fixed with
SAP HANA DATABASE 1.00	SP122	000034 + manual parameter change	
SAP HANA DATABASE 2.0	SP048	000003	
SAP HANA DATABASE 2.0	SP053	000000


SAP Security Patch Day: 2021-02
Version: 001
Date:    10th of Feb 2021
-->
  <!--  [p3-CVSS 4.1] HAN-DB-SEC 0002992154 - [CVE-2020-26834 ] Improper authentication in SAP HANA database (Version 0008)  -->
  <configstore name="HDB_VERSION">
    <checkitem desc="[p3-CVSS 4.1] Note 0002992154 requires revision update" id="00029921548" operator="check_note:0002992154">
      <compliant>
                 (  (NAME = 'VERSION' AND substring(VALUE,0,7) = '2.00.04' AND substring(VALUE,0,11) &gt;= '2.00.048.03')
                 OR (NAME = 'VERSION' AND substring(VALUE,0,7) = '2.00.05' AND substring(VALUE,0,8) &gt;= '2.00.053')
                 OR (NAME = 'VERSION' AND substring(VALUE,0,7) &gt; '2.00.05' ) )  
      </compliant>
      <noncompliant>
	             (  (NAME = 'VERSION' AND substring(VALUE,0,6) = '1.00.0')
	             OR (NAME = 'VERSION' AND substring(VALUE,0,4) = '2.00' AND substring(VALUE,0,7) &lt; '2.00.04')
	             OR (NAME = 'VERSION' AND substring(VALUE,0,7) = '2.00.04' AND NOT(substring(VALUE,0,11) &gt;= '2.00.048.03')) 
                 OR (NAME = 'VERSION' AND substring(VALUE,0,7) = '2.00.05' AND NOT substring(VALUE,0,8) &gt;= '2.00.053')
                 OR (NAME = 'VERSION' AND substring(VALUE,0,6) = '1.00.1' AND NOT(substring(VALUE,0,11) &gt;= '1.00.122.34')) )
      </noncompliant>
      <joinstore name="HDB_VERSION" no_data_found="Yes" not_in_output="Yes">
        <joincompliant>      ( NAME = 'VERSION' AND substring(VALUE,0,4) = '2.00' )
                         OR  ( NAME = 'VERSION' AND substring(VALUE,0,6) = '1.00.1' AND substring(VALUE,0,11) &lt; '1.00.122.34' )
        </joincompliant>
        <joinnoncompliant>   ( NAME = 'VERSION' AND substring(VALUE,0,4) = '2.00' )
                         OR  ( NAME = 'VERSION' AND substring(VALUE,0,6) = '1.00.1' AND substring(VALUE,0,11) &lt; '1.00.122.34' )
       </joinnoncompliant>
      </joinstore>
    </checkitem>
  </configstore>
  <configstore name="HDB_PARAMETER">
    <checkitem desc="[p3-CVSS 4.1] Note 0002992154 requires manual parameter change" id="0002992154" operator="check_note:0002992154">
      <compliant>
              FILE_NAME = 'global.ini' and SECT = 'authentication'  and NAME = 'saml_signature_hash_types'  and not UPPER(VALUE) like '%MD5%' 
    </compliant>
      <noncompliant>      
              FILE_NAME = 'global.ini' and SECT = 'authentication'  and NAME = 'saml_signature_hash_types'  and UPPER(VALUE) like '%MD5%' 
    </noncompliant>
      <joinstore name="HDB_VERSION" no_data_found="Yes" not_in_output="Yes">
        <joincompliant>     NAME = 'VERSION' AND substring(VALUE,0,6) = '1.00.1' AND substring(VALUE,0,11) &gt;= '1.00.122.34'       </joincompliant>
        <joinnoncompliant>  NAME = 'VERSION' AND substring(VALUE,0,6) = '1.00.1' AND substring(VALUE,0,11) &gt;= '1.00.122.34'        </joinnoncompliant>
      </joinstore>
    </checkitem>
  </configstore>
</targetsystem>
