=== FrankBuchholz/frun-csa-policies-best-practices/Schema/csa_policy.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified"><xs:simpleType name="yesnoType"><xs:restriction base="xs:string"><xs:enumeration value="Yes"/><xs:enumeration value="No"/></xs:restriction></xs:simpleType><xs:simpleType name="name_extendedType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/></xs:restriction></xs:simpleType><xs:simpleType name="sci_idType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="20"/></xs:restriction></xs:simpleType><xs:simpleType name="system_typeType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="20"/></xs:restriction></xs:simpleType><xs:simpleType name="hierarchy_levelType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="1"/><xs:pattern value="[23456]"/></xs:restriction></xs:simpleType><xs:simpleType name="descType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/></xs:restriction></xs:simpleType><xs:simpleType name="idType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="20"/></xs:restriction></xs:simpleType><xs:simpleType name="not_foundType"><xs:restriction base="xs:string"><xs:enumeration value="positive"/><xs:enumeration value="negative"/></xs:restriction></xs:simpleType><xs:simpleType name="system_rolesType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="250"/></xs:restriction></xs:simpleType><xs:simpleType name="store_attributeType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="280"/></xs:restriction></xs:simpleType><xs:simpleType name="operatorType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/><xs:pattern value="[Ee][Xx][Ii][Ss][Tt]($|:[\w\d_]{1,256})|[Nn][Oo][Tt]_[Ee][Xx][Ii][Ss][Tt]($|:[\w\d_]{1,256})|[Cc][Hh][Ee][Cc][Kk]_[Nn][Oo][Tt][Ee]|[Cc][Hh][Ee][Cc][Kk]_[Nn][Oo][Tt][Ee]:[0-9]{10}"/></xs:restriction></xs:simpleType><xs:simpleType name="nameType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/></xs:restriction></xs:simpleType><xs:element name="targetsystem"><xs:complexType><xs:sequence><xs:element maxOccurs="unbounded" minOccurs="1" name="configstore"><xs:complexType><xs:sequence><xs:element maxOccurs="unbounded" minOccurs="1" name="checkitem"><xs:complexType><xs:sequence><xs:element name="compliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="complianttext" type="xs:string"/><xs:element name="noncompliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="noncomplianttext" type="xs:string"/><xs:element maxOccurs="unbounded" minOccurs="0" name="joinstore"><xs:complexType><xs:sequence><xs:element name="joincompliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="joincomplianttext" type="xs:string"/><xs:element name="joinnoncompliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="joinnoncomplianttext" type="xs:string"/></xs:sequence><xs:attribute name="name" type="xs:string" use="required"/><xs:attribute default="Yes" name="minus" type="yesnoType" use="optional"/><xs:attribute name="name_extended" type="name_extendedType" use="optional"/><xs:attribute default="No" name="no_data_found" type="yesnoType" use="optional"/><xs:attribute default="No" name="not_in_output" type="yesnoType" use="optional"/><xs:attribute name="sci_id" type="sci_idType" use="optional"/><xs:attribute name="system_type" type="system_typeType" use="optional"/><xs:attribute name="hierarchy_level" type="hierarchy_levelType" use="optional"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="desc" type="descType" use="required"/><xs:attribute name="id" type="idType" use="required"/><xs:attribute default="negative" name="not_found" type="not_foundType" use="optional"/><xs:attribute name="operator" type="operatorType" use="optional"/><xs:attribute name="system_roles" type="system_rolesType" use="optional"/><xs:attribute name="store_attribute" type="store_attributeType" use="optional"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="name" type="nameType" use="required"/><xs:attribute name="name_extended" type="name_extendedType" use="optional"/><xs:attribute name="sci_id" type="sci_idType" use="optional"/><xs:attribute name="system_type" type="system_typeType" use="optional"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="desc" type="descType" use="required"/><xs:attribute name="id" type="idType" use="required"/><xs:attribute default="Yes" name="multisql" type="yesnoType"/></xs:complexType></xs:element></xs:schema>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v1.9.3/BL_S-9.xml
<?xml version="1.0" encoding="utf-16"?>
<!--
This FRUN CSA policy contains rules derived from SAP Security Baseline Template Version 3
Available at: http://support.sap.com/sos

Target system BL_S-9 / Limit Web-Enabled Content

Version: 001
Date:    Feb 02 2018
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="Limit Web-Enabled Content" id="BL_S-9" multisql="Yes" xsi:schemaLocation="csa_policy.xsd">
 <configstore sci_id="" name="SICF_SERVICES" name_extended="">
  <checkitem desc="Deactivate WebService FormToRfc" id="BL_S-9.01" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/FormToRfc/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/FormToRfc/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService IDoc_XML" id="BL_S-9.02" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/IDoc_XML/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/IDoc_XML/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService bsp_veri" id="BL_S-9.03" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/bsp_veri/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/bsp_veri/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService certmap" id="BL_S-9.04" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/certmap/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/certmap/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService certreq" id="BL_S-9.05" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/certreq/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/certreq/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService icf" id="BL_S-9.06" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/icf/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/icf/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService CERTMAP" id="BL_S-9.07" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/its/CERTMAP/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/its/CERTMAP/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService CERTREQ" id="BL_S-9.08" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/its/CERTREQ/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/bsp/sap/its/CERTREQ/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService echo" id="BL_S-9.09" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/echo/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/echo/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService error" id="BL_S-9.10" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/error/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/error/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService report" id="BL_S-9.11" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/report/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/report/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService rfc" id="BL_S-9.12" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/soap/rfc/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/soap/rfc/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService IDoc" id="BL_S-9.13" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/srt/IDoc/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/srt/IDoc/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService webrfc" id="BL_S-9.14" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/webrfc/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/webrfc/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService xrfc" id="BL_S-9.15" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/xrfc/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/xrfc/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Deactivate WebService xrfc_test" id="BL_S-9.16" operator="not_exist:URL">
   <compliant>ICF_NAME like '%'  and URL = '/sap/bc/xrfc_test/' </compliant>
   <complianttext/>
   <noncompliant>ICF_NAME like '%'  and URL = '/sap/bc/xrfc_test/' </noncompliant>
   <noncomplianttext/>
  </checkitem>
 </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v1.9.5/BL_O-1.xml
<?xml version="1.0" encoding="utf-16"?>
<!--
This FRUN CSA policy contains rules derived from SAP Security Baseline Template Version 3
Available at: http://support.sap.com/sos

Target system BL_O-1 / Handling of ABAP Default Users in ABAP Systems

Version: 001
Date:    Feb 02 2018
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="ABAP Default User Handling" id="BL_O-1" multisql="Yes" xsi:schemaLocation="csa_policy.xsd">
  <configstore name="ABAP_INSTANCE_PAHI">
    <checkitem desc="No Login with user sap*" id="BL_O-1.01">
      <compliant>NAME = 'login/no_automatic_user_sapstar'  and VALUE = '1' </compliant>
      <complianttext/>
      <noncompliant>NAME = 'login/no_automatic_user_sapstar'  and not ( VALUE = '1'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
  </configstore>
  <configstore name="STANDARD_USERS">
    <checkitem desc="TMSADM password status client 000" id="BL_O-1.02">
      <compliant>CLIENT = '000'  and USERNAME = 'TMSADM'  and PASSWORD_STATUS = 'CHANGED' </compliant>
      <complianttext/>
      <noncompliant>CLIENT = '000'  and USERNAME = 'TMSADM'  and not ( PASSWORD_STATUS = 'CHANGED'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="TMSADM password status in client != 000" id="BL_O-1.03" not_found="positive">
      <compliant>CLIENT  &lt;&gt; '000' and USERNAME = 'TMSADM'  and EXISTING &lt;&gt; 'X'</compliant>
      <complianttext/>
      <noncompliant>CLIENT &lt;&gt; '000' and USERNAME = 'TMSADM'  and EXISTING = 'X'</noncompliant>
      <noncomplianttext/>
    </checkitem>
    <!-- in case DDIC is supposed to be locked 
    <checkitem desc="DDIC password status in clients != 000" id="BL_O-1.04a">
      <compliant>CLIENT &lt;&gt; '000'  and USERNAME = 'DDIC'  and ( PASSWORD_STATUS = 'CHANGED'  AND LOCKED  = 'X' )</compliant>
      <complianttext/>
      <noncompliant>CLIENT &lt;&gt; '000'  and USERNAME = 'DDIC'  and not ( PASSWORD_STATUS = 'CHANGED'  AND LOCKED  = 'X' )</noncompliant>
      <noncomplianttext/>
    </checkitem>
    -->
    <checkitem desc="DDIC password status changed in all clients" id="BL_O-1.04" not_found="positive">
      <compliant>CLIENT like '%'  and USERNAME = 'DDIC' and ( PASSWORD_STATUS = 'CHANGED' or EXISTING &lt;&gt; 'X'  )</compliant>
      <complianttext/>
      <noncompliant>CLIENT like '%' and USERNAME = 'DDIC'  and not ( PASSWORD_STATUS = 'CHANGED' or EXISTING &lt;&gt; 'X' )</noncompliant>
      <noncomplianttext/>
    </checkitem>
    <!-- in case EARLYWATCH is supposed to be locked 
    <checkitem desc="EARLYWATCH password status" id="BL_O-1.05" not_found="positive">
      <compliant>CLIENT like '%'  and USERNAME = 'EARLYWATCH' and PASSWORD_STATUS = 'CHANGED' and (EXISTING &lt;&gt; 'X'  or LOCKED &lt;&gt; 'X')</compliant>
      <complianttext/>
      <noncompliant>CLIENT like '%'  and USERNAME = 'EARLYWATCH' and ( PASSWORD_STATUS &lt;&gt; 'CHANGED' or ( EXISTING = 'X' and LOCKED = '') or  ( EXISTING = '' ) )</noncompliant>
      <noncomplianttext/>
    </checkitem>
    -->
    <checkitem desc="EARLYWATCH password status" id="BL_O-1.05" not_found="positive">
      <compliant>CLIENT like '%'  and USERNAME = 'EARLYWATCH' and ( PASSWORD_STATUS = 'CHANGED' or EXISTING &lt;&gt; 'X')</compliant>
      <complianttext/>
      <noncompliant>CLIENT like '%'  and USERNAME = 'EARLYWATCH' and not ( PASSWORD_STATUS = 'CHANGED' or EXISTING &lt;&gt; 'X')</noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="SAP* password status" id="BL_O-1.06">
      <compliant>CLIENT like '%'  and USERNAME = 'SAP*'  and PASSWORD_STATUS = 'CHANGED'  and EXISTING = 'X'  and LOCKED = 'X' </compliant>
      <complianttext/>
      <noncompliant>CLIENT like '%'  and USERNAME = 'SAP*'  and not ( PASSWORD_STATUS = 'CHANGED'  and EXISTING = 'X'  and LOCKED = 'X'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="SAPCPIC password status" id="BL_O-1.07">
      <compliant>CLIENT like '%'  and USERNAME = 'SAPCPIC'  and ( PASSWORD_STATUS = 'CHANGED' or EXISTING &lt;&gt; 'X' )</compliant>
      <complianttext/>
      <noncompliant>CLIENT like '%'  and USERNAME = 'SAPCPIC'  and not ( PASSWORD_STATUS &lt;&gt; 'CHANGED' or EXISTING = 'X' )</noncompliant>
      <noncomplianttext/>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v2.4/ABAP_ALL/3ANETENC.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 
Reference:   SAP Security Baseline Template v2.4 (2022/12)
Link:        https://support.sap.com/content/dam/support/en_us/library/ssp/offerings-and-programs/support-services/sap-security-optimization-services-portfolio/Security_Baseline_Template_V2.zip
Version:     001
Date:        2023-04-28
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="[BL2.4] Encryption of Network Connections (ABAP)" id="3ANETENC" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <!-- NETENC-A: Encryption of Network Connections â€“ ABAP-->
  <configstore name="ABAP_INSTANCE_PAHI" sci_id="">
    <checkitem desc="[p3-EXTENDED] Accept insecure SAPGUI logins to SNC-enabled Server" id="NETENC-A_c.1">
      <compliant>       NAME = 'snc/accept_insecure_gui' and (VALUE = '0' or VALUE = 'U')</compliant>
      <complianttext/>
      <noncompliant>    NAME = 'snc/accept_insecure_gui' and not (VALUE = '0' or VALUE = 'U') </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Accept insecure RFC-connections to SNC-enabled Server" id="NETENC-A_c.2a">
      <compliant>       NAME = 'snc/accept_insecure_rfc' and (VALUE = '0' or VALUE = 'U') </compliant>
      <complianttext/>
      <noncompliant>    NAME = 'snc/accept_insecure_rfc' and not (VALUE = '0' or VALUE = 'U') </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Accept insecure RFC-connections to SNC-enabled Server" id="NETENC-A_c.2b">
      <compliant>       NAME = 'snc/accept_insecure_r3int_rfc' and (VALUE = '0' or VALUE = '1') </compliant>
      <complianttext/>
      <noncompliant>    NAME = 'snc/accept_insecure_r3int_rfc' and not ( VALUE = '0' or VALUE = '1') </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Accept only encrypted GUI connections to SNC-enabled Server" id="NETENC-A_c.3">
      <compliant>       NAME = 'snc/only_encrypted_gui' and VALUE = '1' </compliant>
      <complianttext/>
      <noncompliant>    NAME = 'snc/only_encrypted_gui' and VALUE = '1'  </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] Accept only encrypted RFC connections to SNC-enabled Server" id="NETENC-A_c.4">
      <compliant>       NAME = 'snc/only_encrypted_rfc' and VALUE = '1' </compliant>
      <complianttext/>
      <noncompliant>    NAME = 'snc/only_encrypted_rfc' and not VALUE = '1' </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] snc/log_unencrypted_rfc (profile parameter)" id="NETENC-A_d">
      <compliant>       NAME = 'snc/log_unencrypted_rfc' and VALUE = '2' </compliant>
      <complianttext/>
      <noncompliant>    NAME = 'snc/log_unencrypted_rfc' and not VALUE = '2'  </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] ssl/ciphersuites (profile parameter, SAP Note 510007)" id="NETENC-A_f.1">
      <compliant>      NAME = 'ssl/ciphersuites' and VALUE = '135:PFS:HIGH::EC_P256:EC_HIGH' </compliant>
      <complianttext/>
      <noncompliant>   NAME = 'ssl/ciphersuites' and not VALUE = '135:PFS:HIGH::EC_P256:EC_HIGH'  </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] ssl/client_ciphersuites (profile parameter, SAP Note 510007)" id="NETENC-A_f.2">
      <compliant>      NAME = 'ssl/client_ciphersuites' and VALUE = '150:PFS:HIGH::EC_P256:EC_HIGH' </compliant>
      <complianttext/>
      <noncompliant>   NAME = 'ssl/client_ciphersuites' and not VALUE = '150:PFS:HIGH::EC_P256:EC_HIGH'  </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] system/secure_communication (profile parameter, SAP Notes 2040644, 2362078)" id="NETENC-A_e">
      <compliant>       NAME = 'system/secure_communication' and VALUE = 'ON' </compliant>
      <complianttext/>
      <noncompliant>    NAME = 'system/secure_communication' and not VALUE = 'ON'  </noncompliant>
      <noncomplianttext/>
      <joinstore name="COMP_LEVEL" no_data_found="Yes" not_in_output="Yes">
        <joincompliant>        
                       ( component = 'SAP_BASIS' and version = '740' and SP &gt;= '0008' ) OR
                       ( component = 'SAP_BASIS' and version &gt; '740' )
        </joincompliant>
        <joinnoncompliant> 
                       ( component = 'SAP_BASIS' and version = '740' and SP &gt;= '0008' ) OR
                       ( component = 'SAP_BASIS' and version &gt; '740' ) </joinnoncompliant>
      </joinstore>
    </checkitem>
  </configstore>
  <configstore name="COMP_LEVEL" sci-id="S00120">
    <checkitem desc="[p3-EXTENDED] system/secure_communication (profile parameter, SAP Notes 2040644, 2362078)" id="NETENC-A_e">
      <compliant>      ( component = 'SAP_BASIS' and version = '740' and SP &gt;= '0008' ) OR
                       ( component = 'SAP_BASIS' and version &gt; '740' )      
      </compliant>
      <complianttext/>
      <noncompliant>   ( component = 'SAP_BASIS' and version = '740' and SP &lt; '0008' ) OR
                       ( component = 'SAP_BASIS' and version &lt; '740' )
      </noncompliant>
      <noncomplianttext>   system/secure_communication requires upgrade to SAP_BASIS 7.40 SP 8 or higher version
      </noncomplianttext>
      <joinstore name="COMP_LEVEL" no_data_found="Yes" not_in_output="Yes" sci-id="S00120">
        <joincompliant> ( component = 'SAP_BASIS' and version = '740' and SP &lt; '0008' ) OR
                      ( component = 'SAP_BASIS' and version &lt; '740' )
      </joincompliant>
        <joinnoncompliant> 
                      ( component = 'SAP_BASIS' and version = '740' and SP &lt; '0008' ) OR
                      ( component = 'SAP_BASIS' and version &lt; '740' )
      </joinnoncompliant>
      </joinstore>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v2.4/ABAP_ALL/2ACRITD_CSTO.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 
Reference:   SAP Security Baseline Template v2.4 (2022/12)
Link:        https://support.sap.com/content/dam/support/en_us/library/ssp/offerings-and-programs/support-services/sap-security-optimization-services-portfolio/Security_Baseline_Template_V2.zip
Version:     001
Date:        2023-04-28
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="[BL2.4] Protection of Password Hashes (ABAP)" id="2ACRITD_CSTO" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
    <configstore name="AUTH_COMB_USER" sci_id="">
    <checkitem desc="[p2-STANDARD] Users with READHASHTABGRP authorization" id="CRITAU-A_d.2.1" not_found="positive">
      <compliant>         COMB_ID = 'READHASHTABGRP' and
                                    USER like '%' and
                                    ( RC =  'NONE'  or RC = 'OBJECT_NOT_EXISTING' or
                                      LOCKED = 'X' or
                                      INVALID = 'X' )
      </compliant>
      <complianttext/>
      <noncompliant>   COMB_ID = 'READHASHTABGRP' and
                                    USER like '%' and not
                                    ( RC =  'NONE' or RC = 'OBJECT_NOT_EXISTING' or
                                      LOCKED = 'X' or
                                      INVALID = 'X' )
      </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p2-STANDARD] Users with READHASHTABLES authorization" id="CRITAU-A_d.2.2" not_found="positive">
      <compliant>         COMB_ID = 'READHASHTABLES' and
                                    USER like '%' and
                                    ( RC =  'NONE'  or RC = 'OBJECT_NOT_EXISTING' or
                                      LOCKED = 'X' or
                                      INVALID = 'X' )
      </compliant>
      <complianttext/>
      <noncompliant>   COMB_ID = 'READHASHTABLES' and
                                    USER like '%' and not
                                    ( RC =  'NONE' or RC = 'OBJECT_NOT_EXISTING' or
                                      LOCKED = 'X' or
                                      INVALID = 'X' )
      </noncompliant>
      <noncomplianttext/>
    </checkitem>
   </configstore>
   <configstore name="AUTH_COMB_ROLE" sci_id="">
    <checkitem desc="[p2-STANDARD] Roles with READ HASH TABLE GROUP authorization" id="CRITAU-A_d.2.3" not_found="positive">
      <compliant>         COMB_ID = 'READHASHTABGRP' and
                                    ROLE like '%' and
                                    ( RC =  'NONE' or RC = 'OBJECT_NOT_EXISTING' )
      </compliant>
      <complianttext/>
      <noncompliant>   COMB_ID = 'READHASHTABGRP' and
                                    ROLE like '%' and not
                                    ( RC =  'NONE' or RC = 'OBJECT_NOT_EXISTING' )
      </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p2-STANDARD] Roles with READ HASH TABLES authorization" id="CRITAU-A_d.2.4" not_found="positive">
      <compliant>         COMB_ID = 'READHASHTABLES' and
                                    ROLE like '%' and
                                    ( RC =  'NONE' or RC = 'OBJECT_NOT_EXISTING' )
      </compliant>
      <complianttext/>
      <noncompliant>   COMB_ID = 'READHASHTABLES' and
                                    ROLE like '%' and not
                                    ( RC =  'NONE' or RC = 'OBJECT_NOT_EXISTING' )
      </noncompliant>
      <noncomplianttext/>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v1.9.3/BL_S-5.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
This FRUN CSA policy contains rules derived from SAP Security Baseline Template Version 3
Available at: http://support.sap.com/sos

Target system BL_S-5 / JAVA UME Parameters


replaced(SUBSTR_REGEXPR('([[:digit:]]{1,99})'  by lpad(VALUE, 4, '0')  to avoid error '...attribute is not a number...'

Version: 002
Date:    Sept 16 2020
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="SAP BASELINE BL_S-5 (JAVA UME PARAMETERS)" id="BL_S-5" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <configstore name="com.sap.security.core.ume.service">
    <checkitem desc="SAP logon ticket lifetime" id="BL_S-5.01">
      <compliant>NAME = 'login.ticket_lifetime'  and lpad(VALUE, 4, '0') &lt;= '0008' </compliant>
      <complianttext/>
      <noncompliant>NAME = 'login.ticket_lifetime'  and not (lpad(VALUE, 4, '0') &lt;= '0008'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="SAP logon ticket set to HttpOnly" id="BL_S-5.02">
      <compliant>NAME = 'ume.logon.httponlycookie'  and ( VALUE = 'true'  or VALUE = 'TRUE' )</compliant>
      <complianttext/>
      <noncompliant>NAME = 'ume.logon.httponlycookie'  and not ( ( VALUE = 'true'  or VALUE = 'TRUE' ) )</noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="Send SAP logon ticket only via HTTPS" id="BL_S-5.03">
      <compliant>NAME = 'ume.logon.security.enforce_secure_cookie'  and ( VALUE = 'true'  or VALUE = 'TRUE' )</compliant>
      <complianttext/>
      <noncompliant>NAME = 'ume.logon.security.enforce_secure_cookie'  and not ( ( VALUE = 'true'  or VALUE = 'TRUE' ) ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="Disable old password in password allowed" id="BL_S-5.04">
      <compliant>NAME = 'ume.logon.security_policy.oldpass_in_newpass_allowed'  and ( VALUE = 'false'  or VALUE = 'FALSE' )</compliant>
      <complianttext/>
      <noncompliant>NAME = 'ume.logon.security_policy.oldpass_in_newpass_allowed'  and not ( ( VALUE = 'false'  or VALUE = 'FALSE' ) ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="Minimum number of letters and numbers in password" id="BL_S-5.05">
      <compliant>NAME = 'ume.logon.security_policy.password_alpha_numeric_required'  and lpad(VALUE, 4, '0') &gt;= '0001' </compliant>
      <complianttext/>
      <noncompliant>NAME = 'ume.logon.security_policy.password_alpha_numeric_required'  and not ( lpad(VALUE, 4, '0') &gt;= '0001' ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="Minimum Password Length" id="BL_S-5.06">
      <compliant>NAME = 'ume.logon.security_policy.password_min_length'  and lpad(VALUE, 4, '0') &gt;= '0008' </compliant>
      <complianttext/>
      <noncompliant>NAME = 'ume.logon.security_policy.password_min_length'  and not ( lpad(VALUE, 4, '0') &gt;= '0008'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="Minimum number of uppercase and lowercase letters in password required" id="BL_S-5.07">
      <compliant>NAME = 'ume.logon.security_policy.password_mix_case_required'  and lpad(VALUE, 4, '0') &gt;= '0001' </compliant>
      <complianttext/>
      <noncompliant>NAME = 'ume.logon.security_policy.password_mix_case_required'  and not ( lpad(VALUE, 4, '0') &gt;= '0001'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="Minimum number of special characters in passwords" id="BL_S-5.08">
      <compliant>NAME = 'ume.logon.security_policy.password_special_char_required'  and lpad(VALUE, 4, '0') &gt;= '0000' </compliant>
      <complianttext/>
      <noncompliant>NAME = 'ume.logon.security_policy.password_special_char_required'  and not ( lpad(VALUE, 4, '0') &gt;= '0000'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="Disable user ID as part of password" id="BL_S-5.09">
      <compliant>NAME = 'ume.logon.security_policy.userid_in_password_allowed'  and ( VALUE = 'false'  or VALUE = 'FALSE' )</compliant>
      <complianttext/>
      <noncompliant>NAME = 'ume.logon.security_policy.userid_in_password_allowed'  and not ( ( VALUE = 'false'  or VALUE = 'FALSE' ) ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="Disable UME Self Registration" id="BL_S-5.10">
      <compliant>NAME = 'ume.logon.selfreg'  and ( VALUE = 'false'  or VALUE = 'FALSE' )</compliant>
      <complianttext/>
      <noncompliant>NAME = 'ume.logon.selfreg'  and not ( ( VALUE = 'false'  or VALUE = 'FALSE' ) ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
  </configstore>
</targetsystem>
