=== FrankBuchholz/frun-csa-policies-best-practices/Schema/csa_policy.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified"><xs:simpleType name="yesnoType"><xs:restriction base="xs:string"><xs:enumeration value="Yes"/><xs:enumeration value="No"/></xs:restriction></xs:simpleType><xs:simpleType name="name_extendedType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/></xs:restriction></xs:simpleType><xs:simpleType name="sci_idType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="20"/></xs:restriction></xs:simpleType><xs:simpleType name="system_typeType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="20"/></xs:restriction></xs:simpleType><xs:simpleType name="hierarchy_levelType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="1"/><xs:pattern value="[23456]"/></xs:restriction></xs:simpleType><xs:simpleType name="descType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/></xs:restriction></xs:simpleType><xs:simpleType name="idType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="20"/></xs:restriction></xs:simpleType><xs:simpleType name="not_foundType"><xs:restriction base="xs:string"><xs:enumeration value="positive"/><xs:enumeration value="negative"/></xs:restriction></xs:simpleType><xs:simpleType name="system_rolesType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="250"/></xs:restriction></xs:simpleType><xs:simpleType name="store_attributeType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="280"/></xs:restriction></xs:simpleType><xs:simpleType name="operatorType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/><xs:pattern value="[Ee][Xx][Ii][Ss][Tt]($|:[\w\d_]{1,256})|[Nn][Oo][Tt]_[Ee][Xx][Ii][Ss][Tt]($|:[\w\d_]{1,256})|[Cc][Hh][Ee][Cc][Kk]_[Nn][Oo][Tt][Ee]|[Cc][Hh][Ee][Cc][Kk]_[Nn][Oo][Tt][Ee]:[0-9]{10}"/></xs:restriction></xs:simpleType><xs:simpleType name="nameType"><xs:restriction base="xs:string"><xs:minLength value="1"/><xs:maxLength value="256"/></xs:restriction></xs:simpleType><xs:element name="targetsystem"><xs:complexType><xs:sequence><xs:element maxOccurs="unbounded" minOccurs="1" name="configstore"><xs:complexType><xs:sequence><xs:element maxOccurs="unbounded" minOccurs="1" name="checkitem"><xs:complexType><xs:sequence><xs:element name="compliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="complianttext" type="xs:string"/><xs:element name="noncompliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="noncomplianttext" type="xs:string"/><xs:element maxOccurs="unbounded" minOccurs="0" name="joinstore"><xs:complexType><xs:sequence><xs:element name="joincompliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="joincomplianttext" type="xs:string"/><xs:element name="joinnoncompliant" type="xs:string"/><xs:element maxOccurs="1" minOccurs="0" name="joinnoncomplianttext" type="xs:string"/></xs:sequence><xs:attribute name="name" type="xs:string" use="required"/><xs:attribute default="Yes" name="minus" type="yesnoType" use="optional"/><xs:attribute name="name_extended" type="name_extendedType" use="optional"/><xs:attribute default="No" name="no_data_found" type="yesnoType" use="optional"/><xs:attribute default="No" name="not_in_output" type="yesnoType" use="optional"/><xs:attribute name="sci_id" type="sci_idType" use="optional"/><xs:attribute name="system_type" type="system_typeType" use="optional"/><xs:attribute name="hierarchy_level" type="hierarchy_levelType" use="optional"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="desc" type="descType" use="required"/><xs:attribute name="id" type="idType" use="required"/><xs:attribute default="negative" name="not_found" type="not_foundType" use="optional"/><xs:attribute name="operator" type="operatorType" use="optional"/><xs:attribute name="system_roles" type="system_rolesType" use="optional"/><xs:attribute name="store_attribute" type="store_attributeType" use="optional"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="name" type="nameType" use="required"/><xs:attribute name="name_extended" type="name_extendedType" use="optional"/><xs:attribute name="sci_id" type="sci_idType" use="optional"/><xs:attribute name="system_type" type="system_typeType" use="optional"/></xs:complexType></xs:element></xs:sequence><xs:attribute name="desc" type="descType" use="required"/><xs:attribute name="id" type="idType" use="required"/><xs:attribute default="Yes" name="multisql" type="yesnoType"/></xs:complexType></xs:element></xs:schema>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v2.2/HANA_ALL/BL2_APPLICATION-H.xml
<?xml version="1.0" encoding="utf-8"?>
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="[BL 2.2] Application - HANA" id="BL22_APPLICATION-H" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <!-- STDUSR-H: Standard Users in HANA -->
  <configstore name="HDB_SYSTEM_USER">
    <checkitem desc="[p2-STANDARD] SYSTEM user is deactivated" id="STDUSR-H">
      <compliant>    USER_NAME = 'SYSTEM' and VALID_FROM like '%' and VALID_UNTIL like '%' and DEACTIVATION_TIME like '%' and LOWER(USER_DEACTIVATED) = 'true' </compliant>
      <noncompliant> USER_NAME = 'SYSTEM' and VALID_FROM like '%' and VALID_UNTIL like '%' and DEACTIVATION_TIME like '%' and not LOWER(USER_DEACTIVATED) = 'true' </noncompliant>
    </checkitem>
  </configstore>
  <!-- PWDPOL-H: Password Policy - HANA (SystemDB) -->
  <configstore name="HDB_PARAMETER">
    <checkitem desc="[p1-CRITICAL] Password Policy - minimal password length" id="PWDPOL-H_a.1" system_attributes="DB_SYSTEMDB:TRUE">
      <compliant>    FILE_NAME = 'nameserver.ini'  and TENANT like '%'  and HOST like '%'  and 
                     SECT = 'password policy'  and 
                     NAME = 'minimal_password_length'  and 
                     LAYER like '%'  and 
                     lpad(VALUE,4,'0') &gt;= '0008' 
      </compliant>
      <complianttext/>
      <noncompliant> FILE_NAME = 'nameserver.ini'  and TENANT like '%'  and HOST like '%'  and 
                     SECT = 'password policy'  and 
                     NAME = 'minimal_password_length'  and 
                     LAYER like '%'  and 
                     NOT lpad(VALUE,4,'0') &gt;= '0008'
      </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p1-CRITICAL] Password Policy: Unused initial Password Lifetime" id="PWDPOL-H_a.2" system_attributes="DB_SYSTEMDB:TRUE">
      <compliant>    FILE_NAME = 'nameserver.ini'  and TENANT like '%'  and HOST like '%'  and 
                     SECT = 'password policy'  and (NAME = 'maximum_unused_inital_password_lifetime' OR NAME = 'maximum_unused_initial_password_lifetime') and 
                     LAYER like '%'  and 
                     lpad(VALUE,4,'0') between '0001' and '0014'  
      </compliant>
      <complianttext/>
      <noncompliant> FILE_NAME = 'nameserver.ini'  and TENANT like '%'  and HOST like '%'  and 
                     SECT = 'password policy'  and (NAME = 'maximum_unused_inital_password_lifetime' OR NAME = 'maximum_unused_initial_password_lifetime') and 
                     LAYER like '%'  and  
                     NOT lpad(VALUE,4,'0') between '0001' and '0014'  
      </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p2-STANDARD] Password Policy: First Change" id="PWDPOL-H_b" system_attributes="DB_SYSTEMDB:TRUE">
      <compliant>    FILE_NAME = 'nameserver.ini' and 
                     SECT = 'password policy' and 
                     NAME = 'force_first_password_change' and 
                     LOWER(VALUE) = 'true' and 
                     LAYER like '%' and HOST like '%' and TENANT like '%' 
      </compliant>
      <noncompliant> FILE_NAME = 'nameserver.ini' and 
                     SECT = 'password policy' and 
                     NAME = 'force_first_password_change' and 
                     NOT LOWER(VALUE) = 'true' and 
                     LAYER like '%' and HOST like '%' and TENANT like '%' 
      </noncompliant>
    </checkitem>
    <checkitem desc="[p1-CRITICAL] Password Policy: Unused Productive Password Lifetime" id="PWDPOL-H_c" system_attributes="DB_SYSTEMDB:TRUE">
      <compliant>    FILE_NAME = 'nameserver.ini' and 
                     SECT = 'password policy' and 
                     NAME = 'maximum_unused_productive_password_lifetime' and  
                     lpad(VALUE,4,'0') between '0001' and '0090' and 
                     LAYER like '%' and HOST like '%' and TENANT like '%' 
      </compliant>
      <noncompliant> FILE_NAME = 'nameserver.ini' and 
                     SECT = 'password policy' and 
                     NAME = 'maximum_unused_productive_password_lifetime' and not
                     lpad(VALUE,4,'0') between '0001' and '0090' and 
                     LAYER like '%' and HOST like '%' and TENANT like '%' 
      </noncompliant>
    </checkitem>
    <!--  PWDPOL-H: Password Policy - HANA (TenantDB) -->
    <checkitem desc="[p1-CRITICAL] Password Policy - minimal password length" id="PWDPOL-H_a.1" system_attributes="DB_TENANT:TRUE">
      <compliant>    FILE_NAME = 'indexserver.ini'  and TENANT like '%'  and HOST like '%'  and 
                     SECT = 'password policy'  and 
                     NAME = 'minimal_password_length'  and 
                     LAYER like '%'  and 
                     lpad(VALUE,4,'0') &gt;= '0008' 
      </compliant>
      <complianttext/>
      <noncompliant> FILE_NAME = 'indexserver.ini'  and TENANT like '%'  and HOST like '%'  and 
                     SECT = 'password policy'  and 
                     NAME = 'minimal_password_length'  and 
                     LAYER like '%'  and 
                     NOT lpad(VALUE,4,'0') &gt;= '0008' 
      </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p1-CRITICAL] Password Policy: Unused initial Password Lifetime" id="PWDPOL-H_a.2" system_attributes="DB_TENANT:TRUE">
      <compliant>    FILE_NAME = 'indexserver.ini'  and TENANT like '%'  and HOST like '%'  and TENANT like '%' and
                     SECT = 'password policy'  and 
                     (NAME = 'maximum_unused_inital_password_lifetime' OR NAME = 'maximum_unused_initial_password_lifetime')  and 
                     LAYER like '%'  and  
                     lpad(VALUE,4,'0') between '0001' and '0014'  
      </compliant>
      <complianttext/>
      <noncompliant> FILE_NAME = 'indexserver.ini'  and TENANT like '%'  and HOST like '%'  and TENANT like '%' and 
                     SECT = 'password policy'  and 
                     (NAME = 'maximum_unused_inital_password_lifetime' OR NAME = 'maximum_unused_initial_password_lifetime') and 
                     LAYER like '%'  and NOT 
                      lpad(VALUE,4,'0') between '0001' and '0014'  
      </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p2-STANDARD] Password Policy: First Change" id="PWDPOL-H_b" system_attributes="DB_TENANT:TRUE">
      <compliant>    FILE_NAME = 'indexserver.ini' and  
                     SECT = 'password policy' and 
                     NAME = 'force_first_password_change' and 
                     LOWER(VALUE) = 'true'  and 
                     LAYER like '%' and HOST like '%' and TENANT like '%' 
      </compliant>
      <noncompliant> FILE_NAME = 'indexserver.ini' and 
                     SECT = 'password policy' and 
                     NAME = 'force_first_password_change' and 
                     NOT LOWER(VALUE) = 'true'  and 
                     LAYER like '%' and HOST like '%' and TENANT like '%' 
      </noncompliant>
    </checkitem>
    <checkitem desc="[p1-CRITICAL] Password Policy: Unused Productive Password Lifetime" id="PWDPOL-H_c" system_attributes="DB_TENANT:TRUE">
      <compliant>    FILE_NAME = 'indexserver.ini' and  HOST like '%' and TENANT like '%' and 
                     SECT = 'password policy' and 
                     NAME = 'maximum_unused_productive_password_lifetime' and 
                     LAYER like '%' and
                     lpad(VALUE,4,'0') between '0001' and '0090' 
      </compliant>
      <noncompliant> FILE_NAME = 'indexserver.ini' and HOST like '%' and TENANT like '%' and
                     SECT = 'password policy' and 
                     NAME = 'maximum_unused_productive_password_lifetime' and 
                     LAYER like '%' and 
                     NOT lpad(VALUE,4,'0') between '0001' and '0090' 
      </noncompliant>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v1.9.3/BL_I-5.xml
<?xml version="1.0" encoding="utf-16"?>
<!--
This FRUN CSA policy contains rules derived from SAP Security Baseline Template Version 3
Available at: http://support.sap.com/sos

Target system BL_I-5 / Web Dispatcher Security
   BL_I-5.03   added    server_port_0 and brackets

Version: 002
Date:    Nov 28 2019

Version: 003
Date:    Jan 22 2020
    BL_I-5.03   removed   server_port_0
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="Web Dispatcher Security" id="BL_I-5" multisql="Yes" xsi:schemaLocation="csa_policy.xsd">
 <configstore  name="ABAP_INSTANCE_PAHI">
  <checkitem desc="Web based administration" id="BL_I-5.01">
   <compliant>NAME = 'icm/HTTP/admin_0'  and VALUE like_regexpr '.*CLIENTHOST=.*' </compliant>
   <complianttext/>
   <noncompliant>NAME = 'icm/HTTP/admin_0'  and not ( VALUE like_regexpr '.*CLIENTHOST=.*'  ) </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Directory for ICM error templates" id="BL_I-5.02">
   <compliant>NAME = 'icm/HTTP/error_templ_path'  and VALUE like_regexpr '.*data/icmerror' </compliant>
   <complianttext/>
   <noncompliant>NAME = 'icm/HTTP/error_templ_path'  and not ( VALUE like_regexpr '.*data/icmerror'  ) </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="ICM server port specification" id="BL_I-5.03">
   <compliant>( ( NAME like 'icm/server_port_1' and VALUE like '%PROT=HTTPS%' )
                          or ( NAME like 'icm/server_port_2' and VALUE like '%PROT=HTTPS%' )
                          or ( NAME like 'icm/server_port_3' and VALUE like '%PROT=HTTPS%' )
                          or ( NAME like 'icm/server_port_4' and VALUE like '%PROT=HTTPS%' )
                          or ( NAME like 'icm/server_port_5' and VALUE like '%PROT=HTTPS%' )
                          or ( NAME like 'icm/server_port_6' and VALUE like '%PROT=HTTPS%' )
                          or ( NAME like 'icm/server_port_7' and VALUE like '%PROT=HTTPS%' )
                          or ( NAME like 'icm/server_port_8' and VALUE like '%PROT=HTTPS%' )
			  or ( NAME like 'icm/server_port_9' and VALUE like '%PROT=HTTPS%' ))
   </compliant>
   <complianttext/>
   <noncompliant>( ( NAME like 'icm/server_port_1' and VALUE like '%PROT=HTTP,%' )
                          and ( NAME like 'icm/server_port_2' and VALUE like '%PROT=HTTP,%' )
                          and ( NAME like 'icm/server_port_3' and VALUE like '%PROT=HTTP,%' )
                          and ( NAME like 'icm/server_port_4' and VALUE like '%PROT=HTTP,%' )
                          and ( NAME like 'icm/server_port_5' and VALUE like '%PROT=HTTP,%' )
                          and ( NAME like 'icm/server_port_6' and VALUE like '%PROT=HTTP,%' )
                          and ( NAME like 'icm/server_port_7' and VALUE like '%PROT=HTTP,%' )
                          and ( NAME like 'icm/server_port_8' and VALUE like '%PROT=HTTP,%' )
			  and ( NAME like 'icm/server_port_9' and VALUE like '%PROT=HTTP,%' ))
   </noncompliant>
   <noncomplianttext/>
  </checkitem>
  <checkitem desc="Form of HTTP error pages (short or detailed) " id="BL_I-5.05">
   <compliant>NAME = 'is/HTTP/show_detailed_errors'  and VALUE = 'FALSE' </compliant>
   <complianttext/>
   <noncompliant>NAME = 'is/HTTP/show_detailed_errors'  and not ( VALUE = 'FALSE'  ) </noncompliant>
   <noncomplianttext/>
  </checkitem>
 </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v1.9.3/BL_I-13.xml
<?xml version="1.0" encoding="utf-8"?>
<!--
This FRUN CSA policy contains rules derived from SAP Security Baseline Template Version 3
Available at: http://support.sap.com/sos

Target system BL_1-13 / SAP HANA Security in general (only HANA Parameter checks)

Version: 002
   replaced integer ((SUBSTR_REGEXPR('([[:digit:]]{1,99})' IN VALUE))) comparison by lpad 
Date:    Mar 27 2020
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="SAP HANA Security" id="BL_I-13" multisql="Yes" xsi:schemaLocation="csa_policy.xsd">
  <configstore name="HDB_PARAMETER">
    <checkitem desc="HANA internal communication" id="BL_I-13.01">
      <compliant>FILE_NAME = 'global.ini'  and TENANT like '%'  and HOST like '%'  and SECT = 'communication'  and NAME = 'listeninterface'  and LAYER like '%'  and VALUE &lt;&gt; '.global' </compliant>
      <complianttext/>
      <noncompliant>FILE_NAME = 'global.ini'  and TENANT like '%'  and HOST like '%'  and SECT = 'communication'  and NAME = 'listeninterface'  and LAYER like '%'  and not ( VALUE &lt;&gt; '.global'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="Password Policy - First Change" id="BL_I-13.02">
      <compliant>FILE_NAME = 'indexserver.ini'  and TENANT like '%'  and HOST like '%'  and SECT = 'password policy'  and NAME = 'force_first_password_change'  and LAYER like '%'  and VALUE like 'true' </compliant>
      <complianttext/>
      <noncompliant>FILE_NAME = 'indexserver.ini'  and TENANT like '%'  and HOST like '%'  and SECT = 'password policy'  and NAME = 'force_first_password_change'  and LAYER like '%'  and not ( VALUE like 'true'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>

    <checkitem desc="Password Policy - unused password lifetime" id="BL_I-13.03">
      <compliant>FILE_NAME = 'indexserver.ini'  and TENANT like '%'  and HOST like '%'  and SECT = 'password policy'  and (NAME = 'maximum_unused_inital_password_lifetime' OR NAME = 'maximum_unused_initial_password_lifetime')  and LAYER like '%'  and lpad(VALUE,8,'0') &lt;= '00000007' </compliant>
      <complianttext/>
      <noncompliant>FILE_NAME = 'indexserver.ini'  and TENANT like '%'  and HOST like '%'  and SECT = 'password policy'  and (NAME = 'maximum_unused_inital_password_lifetime' OR NAME = 'maximum_unused_initial_password_lifetime') and LAYER like '%'  and not ( lpad(VALUE,8,'0') &lt;= '00000007' ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="Password Policy - minimal password length" id="BL_I-13.04">
      <compliant>FILE_NAME = 'indexserver.ini'  and TENANT like '%'  and HOST like '%'  and SECT = 'password policy'  and NAME = 'minimal_password_length'  and LAYER like '%'  and lpad(VALUE,4,'0') &gt;= '0008' </compliant>
      <complianttext/>
      <noncompliant>FILE_NAME = 'indexserver.ini'  and TENANT like '%'  and HOST like '%'  and SECT = 'password policy'  and NAME = 'minimal_password_length'  and LAYER like '%'  and not (lpad(VALUE,4,'0') &gt;= '0008') </noncompliant>
      <noncomplianttext/>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v2.4/ABAP_ALL/3ARFCGW.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 
Reference:   SAP Security Baseline Template v2.4 (2022/12)
Link:        https://support.sap.com/content/dam/support/en_us/library/ssp/offerings-and-programs/support-services/sap-security-optimization-services-portfolio/Security_Baseline_Template_V2.zip
Version:     001
Date:        2023-04-28
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="[BL2.4] RFC Gateway Security Options (ABAP)" id="3ARFCGW" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <!-- RFCGW-A: RFC Gateway Security (part of application server ABAP) -->
  <configstore name="ABAP_INSTANCE_PAHI">
    <checkitem desc="[p3-EXTENDED] acceptable method to start programs via the RFC Gateway " id="RFCGW-A_g">
      <compliant>      NAME = 'gw/rem_start'  and (VALUE = 'DISABLED' or VALUE = 'SSH_SHELL' )  </compliant>
      <complianttext/>
      <noncompliant>   NAME = 'gw/rem_start'  and not (VALUE = 'DISABLED' or VALUE = 'SSH_SHELL' ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p3-EXTENDED] ACL file prxyinfo is maitained" id="RFCGW-A_h">
      <compliant>      NAME = 'gw/acl_mode_proxy'  and VALUE = '1'  </compliant>
      <complianttext/>
      <noncompliant>   NAME = 'gw/acl_mode_proxy'  and not VALUE = '1'  </noncompliant>
      <noncomplianttext/>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v2.2/ABAP_APPLICATION/BL2_SSO-A.xml
<?xml version="1.0" encoding="utf-8"?>
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="[BL 2.2] Single Sign-On - ABAP" id="BL22_SSO-A" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <!-- SSO-A: Single Sign-On â€“ ABAP -->
  <configstore name="ABAP_INSTANCE_PAHI">
    <checkitem desc="[p2-STANDARD] Generate ticket only via https" id="SSO-A_a">
      <compliant>          NAME = 'login/ticket_only_by_https'  and  VALUE = '1'     </compliant>
      <complianttext/>
      <noncompliant>    NAME = 'login/ticket_only_by_https'  and VALUE != '1'    </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p2-STANDARD] Ticket only back to creating host" id="SSO-A_b">
      <compliant>          NAME = 'login/ticket_only_to_host'  and VALUE = '1'       </compliant>
      <complianttext/>
      <noncompliant>    NAME = 'login/ticket_only_to_host'  and VALUE != '1'     </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p2-STANDARD] Set HTTPonly-Flag for Cookies" id="SSO-A_c">
      <compliant>          NAME = 'icf/set_HTTPonly_flag_on_cookies'  and not ( VALUE = '1'or VALUE = '3')   </compliant>
      <complianttext/>
      <noncompliant>    NAME = 'icf/set_HTTPonly_flag_on_cookies'  and ( VALUE = '1'or VALUE = '3')         </noncompliant>
      <noncomplianttext/>
    </checkitem>
  </configstore>
</targetsystem>

=== FrankBuchholz/frun-csa-policies-best-practices/BaselinePolicies/SOS/v2.4/ABAP_ALL/2ACRITD.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- 
Reference:   SAP Security Baseline Template v2.4 (2022/12)
Link:        https://support.sap.com/content/dam/support/en_us/library/ssp/offerings-and-programs/support-services/sap-security-optimization-services-portfolio/Security_Baseline_Template_V2.zip
Version:     001
Date:        2023-04-28
-->
<targetsystem xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" desc="[BL2.4] Protection of Password Hashes (ABAP)" id="2ACRITD" multisql="Yes" version="0000" xsi:schemaLocation="csa_policy.xsd">
  <configstore name="TDDAT">
    <checkitem desc="[p2-STANDARD] Access to table USH02 protected" id="CRITAU-A_d.1.1">
      <compliant>TABNAME = 'USH02'  and CCLASS = 'SPWD' </compliant>
      <complianttext/>
      <noncompliant>TABNAME = 'USH02'  and not ( CCLASS = 'SPWD'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p2-STANDARD] Access to table USR02 protected" id="CRITAU-A_d.1.2">
      <compliant>TABNAME = 'USR02'  and CCLASS = 'SPWD' </compliant>
      <complianttext/>
      <noncompliant>TABNAME = 'USR02'  and not ( CCLASS = 'SPWD'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
    <checkitem desc="[p2-STANDARD] Access to table USRPWDHISTORY protected" id="CRITAU-A_d.1.3">
      <compliant>TABNAME = 'USRPWDHISTORY'  and CCLASS = 'SPWD' </compliant>
      <complianttext/>
      <noncompliant>TABNAME = 'USRPWDHISTORY'  and not ( CCLASS = 'SPWD'  ) </noncompliant>
      <noncomplianttext/>
    </checkitem>
  </configstore>
</targetsystem>
